### ISSUE TITLE
🐛 Bug: Cannot find module '~~~/ts-api-utils/lib/tokens' from comments.js

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#232]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

`import * as tsutils from "ts-api-utils"` should not throw an error.

### Actual

```plaintext
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/josh/repos/ts-api-utils/lib/tokens' imported from /Users/josh/repos/ts-api-utils/lib/comments.js
```

### Additional Info

Right now, this repo's source code needs to write `import` statements with explicit `.js` extensions for relative file paths:

```ts
import { greet } from "./greet.js";
```

It does so because the output ESM (ECMAScript Modules) `.js` files need that explicit `.js` extension. The ESM import algorithm doesn't allow omitting it. You can read more at https://www.typescriptlang.org/docs/handbook/esm-node.html.

But, I broke this in 620c2536ef5c28f372412d464cb10c7be708a995 😱 

```ts
import { forEachToken } from "./tokens";
```
